### ISSUE TITLE
Error running on certain repositories

### ISSUE THREAD

**Issue by devinc13** [Hoverbear/transit#7]
When running transit on Ruby on Rails, Bootstrap or Node, we are getting the following error:

```
thread '<main>' panicked at 'Couldn't parse line content for deleted', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/option.rs:330
thread '<main>' panicked at 'Box<Any>', /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/git2-0.2.1/src/panic.rs:32
```

Thanks guys!!

**Comment by Hoverbear** [comment]
Using `RUST_BACKTRACE=1 ./target/release/transit ../servo` generates a similar error:

```
➜  transit git:(master) ✗ RUST_BACKTRACE=1 ./target/release/transit ../servo
thread '<main>' panicked at 'Couldn't parse line content for added', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/option.rs:330
stack backtrace:
   1:        0x101beb36d - sys::backtrace::write::h2f0eebf22a012f95KDA
   2:        0x101bef10d - panicking::on_panic::h2d130f87f4af87adMsJ
   3:        0x101bdf449 - rt::unwind::begin_unwind_inner::h1a1f64f2e0909849ibJ
   4:        0x101bdf8ce - rt::unwind::begin_unwind_fmt::hf4597af2239ff3f4T9I
   5:        0x101bee99d - rust_begin_unwind
   6:        0x101c0e415 - panicking::panic_fmt::hb6f0d77608e09e9eIZs
   7:        0x101b4f690 - rt::unwind::try::try_fn::h15902859234708921291
   8:        0x101bf0ee8 - rust_try_inner
   9:        0x101bf0ed5 - rust_try
  10:        0x101b4e1db - diff::Diff::print::print::h8324477451254613936
  11:        0x101bb4c78 - git_xdiff_cb
  12:        0x101bde03d - xdl_emit_diffrec
  13:        0x101bdbc0d - xdl_emit_diff
  14:        0x101bdb3c7 - xdl_diff
  15:        0x101bb484b - git_xdiff
  16:        0x101bb35c5 - diff_patch_generate
  17:        0x101bb34de - git_diff_foreach
  18:        0x101bb3cbf - git_diff_print
  19:        0x101b46b11 - find_moves::h330ec262249cb82e57a
  20:        0x101b44400 - main::h17ad3566623297299ca
  21:        0x101bf0ee8 - rust_try_inner
  22:        0x101bf0ed5 - rust_try
  23:        0x101befab7 - rt::lang_start::hf717d7cbaad9f8612mJ
thread '<main>' panicked at 'Box<Any>', /Users/hoverbear/.cargo/registry/src/github.com-1ecc6299db9ec823/git2-0.2.1/src/panic.rs:32
stack backtrace:
   1:        0x101beb36d - sys::backtrace::write::h2f0eebf22a012f95KDA
   2:        0x101bef10d - panicking::on_panic::h2d130f87f4af87adMsJ
   3:        0x101bdf449 - rt::unwind::begin_unwind_inner::h1a1f64f2e0909849ibJ
   4:        0x101ba094d - rt::unwind::begin_unwind::h17565742466719359312
   5:        0x101ba07bb - panic::check::h96e52665e8dcfc81gNb
   6:        0x101b46b2d - find_moves::h330ec262249cb82e57a
   7:        0x101b44400 - main::h17ad3566623297299ca
   8:        0x101bf0ee8 - rust_try_inner
   9:        0x101bf0ed5 - rust_try
  10:        0x101befab7 - rt::lang_start::hf717d7cbaad9f8612mJ
```

Looks like it's occurring in `print()`

Here's the code:

``` rust
        match line.origin() {
            // Additions
            '+' | '>' => {
                added.push_str(str::from_utf8(line.content())
                    .ok().expect("Couldn't parse line content for added"));
```

``` rust
            // Deletions
            '-' | '<' => {
                deleted.push_str(str::from_utf8(line.content())
                    .ok().expect("Couldn't parse line content for deleted"));
```

So it looks like we're being [passed is ill-formatted](http://doc.rust-lang.org/std/str/trait.FromStr.html#tymethod.from_str). It'd be interesting to see what exactly it's choking on.

**Comment by Hoverbear** [comment]
After printing out the relevant bytes running on `servo` I saw this:

```
...
Ok("           attribute DOMString shape;\n")
Ok(" * License, v. 2.0. If a copy of the MPL was not distributed with this file,\n")
Ok(" * You can obtain one at http://mozilla.org/MPL/2.0/.\n")
Ok(" *\n")
Ok(" * The origin of this IDL file is\n")
Ok(" * http://www.whatwg.org/specs/web-apps/current-work/#the-applet-element\n")
Ok(" *\n")
Err(InvalidByte(3))
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidByte(3)', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:744
thread '<main>' panicked at 'Box<Any>', /Users/hoverbear/.cargo/registry/src/github.com-1ecc6299db9ec823/git2-0.2.1/src/panic.rs:32
```

**Comment by Hoverbear** [comment]
After falling back to default values on invalid UTF-8 strings I was able to get this to work. Please note this may affect accuracy since they may not be counted as lines in output.

Hmm, didn't mean to close this.

**Comment by Hoverbear** [comment]
Hmm, didn't mean to close this.

**Comment by devinc13** [comment]
Just finished running transit on Ruby on Rails, Bootstrap and Node! It works great now! Thanks guys! =)

**Comment by Hoverbear** [comment]
@devinc13 Awesome! Good results?
